name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16

  test-action:
    runs-on: ubuntu-latest
    needs: build-docker-image

    steps:
      - name: generate-snake-game-from-github-contribution-grid
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: platane
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: ensure the generated file exists
        run: |
          ls -l ${{ steps.snake-gif.outputs.gif_out_path }}
          test -f ${{ steps.snake-gif.outputs.gif_out_path }}
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}
